export const GET_LINK_REQUEST = 'GET_LINK_REQUEST'
export const GET_LINK_SUCCESS = 'GET_LINK_SUCCESS'
export const GET_LINK_FAIL = 'GET_LINK_FAIL'
export const GET_LINK_RESET = 'GET_LINK_RESET'

export const SHORTEN_LINK_REQUEST = 'SHORTEN_LINK_REQUEST'
export const SHORTEN_LINK_SUCCESS = 'SHORTEN_LINK_SUCCESS'
export const SHORTEN_LINK_FAIL = 'SHORTEN_LINK_FAIL'

export const DELETE_LINK_REQUEST = 'DELETE_LINK_REQUEST'
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS'
export const DELETE_LINK_FAIL = 'DELETE_LINK_FAIL'
